#!/usr/bin/env bash
set -eu

# licensed under Apache License 2.0

. "$(dirname "${BASH_SOURCE[0]}")/setup"

if (( $# < 1 )) || [[ "${1:-}" == "help" ]]; then
  echo "link TARGET"
  echo ""
  echo "Creates a symbolic link from '<name>/<version>' at TARGET "
  echo "to this project directory. If TARGET is set to @local or @preview,"
  echo "the local Typst package directory will be used so that the package"
  echo "gets installed for local use."
  echo "The name and version are read from 'typst.toml' in the project root."
  echo ""
  echo "Local package prefix: $DATA_DIR/typst/package/local"
  echo "Local preview package prefix: $DATA_DIR/typst/package/preview"
  exit 1
fi

TARGET="$(resolve-target "${1:?Missing target path, @local or @preview}")"
echo "Install dir: $TARGET"

PKGDIR="${TARGET:?}/${PKG_PREFIX:?}"
TARGET="${PKGDIR}/${VERSION:?}"
if [ ! -e "$TARGET" ]; then
	mkdir -p "$PKGDIR"

	echo "Linked from: $TARGET"
	ln -s "$PWD" "$TARGET"
else
	echo "Version already exists: $TARGET"
fi
